### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by NicWayand** [cistools/collocate#1]
Hi @duncanwp, first thanks for writing this great package!

I got the below error upon installing with:
`pip install .`

`error in collocate setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.`

[Help online](https://github.com/rm-hull/luma.examples/issues/45) suggested updating setuptools but that didn't work for me.

Removing `extras_require=optional_dependencies,` in setup.py temporarily allowed successful installation. Maybe you or someone else with better knowledge of dependency syntax can help?

**Comment by duncanwp** [comment]
No problem - I hope it's useful! 

Thanks for pointing this out, it should be fixed now in the latest version.
