### ISSUE TITLE
Grid (data) Dataset cannot have latitude/longitude as dims

### ISSUE THREAD

**Issue by NicWayand** [cistools/collocate#2]
Due to the way the data variable in collocate() is converted to a dataframe, if data has latitude and longitude as dims (instead of through dummey x/y dims) it will fail when [indexing data. ](https://github.com/cistools/collocate/blob/master/collocate/__init__.py#L45)

I have made an example notebook that shows 3 possible dims configurations. The 3rd one fails, and below a workaround by swamping dims with dummy variables. 

https://github.com/NicWayand/collocate/blob/master/Test_dim_issue.ipynb

There is probably a better way to do this in the to_dataframe() step.

**Comment by duncanwp** [comment]
Thanks for the detailed report Nic - you were right about the to_dataframe() step. I've added a .reset_index() call to ensure the resulting DataFrames are really flat.

**Comment by NicWayand** [comment]
Thanks!
